label_templates = {
    "LCRY-1700": {
        "label_width_in": 1.28,
        "label_height_in": 0.5,
        "top_margin_in": 0.24,
        "side_margin_in": 0.77,
        "vertical_pitch_in": 0.63,
        "horizontal_pitch_in": 1.4,
        "labels_across": 5,
        "labels_down": 17,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "LCRY-1200": {
        "label_width_in": 1.5,
        "label_height_in": 0.75,
        "top_margin_in": 0.31,
        "side_margin_in": 0.25,
        "vertical_pitch_in": 0.88,
        "horizontal_pitch_in": 1.63,
        "labels_across": 5,
        "labels_down": 12,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "LCRY-2380": {
        "label_width_in": 0.94,
        "label_height_in": 0.5,
        "top_margin_in": 0.24,
        "side_margin_in": 0.56,
        "vertical_pitch_in": 0.63,
        "horizontal_pitch_in": 1.07,
        "labels_across": 7,
        "labels_down": 17,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "LCRY-1100": {
        "label_width_in": 1.69,
        "label_height_in": 0.75,
        "top_margin_in": 0.63,
        "side_margin_in": 0.7,
        "vertical_pitch_in": 0.75,
        "horizontal_pitch_in": 1.8,
        "labels_across": 4,
        "labels_down": 13,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "LCRY-1258": {
        "label_width_in": 2.625,
        "label_height_in": 1.0,
        "top_margin_in": 0.5,
        "side_margin_in": 0.19,
        "vertical_pitch_in": 1.0,
        "horizontal_pitch_in": 2.75,
        "labels_across": 3,
        "labels_down": 10,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "SIDE-1000": {
        "label_width_in": 1.5,
        "label_height_in": 0.25,
        "top_margin_in": 0.62,
        "side_margin_in": 0.5,
        "vertical_pitch_in": 0.25,
        "horizontal_pitch_in": 2.0,
        "labels_across": 4,
        "labels_down": 39,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
}
