
class LabelSpec:
    def __init__(self, **kwargs):
        self.presettype = kwargs.get("presettype")
        self.copiesperlabel = kwargs.get("copiesperlabel")
        self.multi_copiesperlabel = kwargs.get("multi_copiesperlabel")
        self.textboxformatinput = kwargs.get("textboxformatinput")
        self.labeltemplate = kwargs.get("labeltemplate")
        self.fontname = kwargs.get("fontname")
        self.fontsize = kwargs.get("fontsize")
        self.alignment = kwargs.get("text_alignment", "Center")
        self.outputfilenameprefix = kwargs.get("outputfilenameprefix")
        self.output_add_date = kwargs.get("output_add_date")
        self.outputformat = kwargs.get("outputformat")
        self.truncation_indices = kwargs.get("truncation_indices")
        self.text_box_input = kwargs.get("text_box_input")
        self.identical_or_incremental = kwargs.get("identical_or_incremental")
        self.color_theme = kwargs.get("color_theme")
        self.ui_layout = kwargs.get("ui_layout", {})
        self.partialsheet = kwargs.get("partialsheet")
        self.row_start = kwargs.get("row_start")
        self.row_end = kwargs.get("row_end")
        self.col_start = kwargs.get("col_start")
        self.col_end = kwargs.get("col_end")
        self.pages_of_labels = kwargs.get("pages_of_labels", 1)
        self.date_format = kwargs.get("date_format")
        self.sample_filename = kwargs.get("sample_filename", None)
        self.remove_duplicates = kwargs.get("remove_duplicates")