label_templates = {
    "LCRY-1700": {
        "display_name": "Cryo-Babies 1.28 x 0.50",
        "label_width_in": 1.28,
        "label_height_in": 0.5,
        "top_margin_in": 0.24,
        "side_margin_in": 0.77,
        "vertical_pitch_in": 0.63,
        "horizontal_pitch_in": 1.4,
        "labels_across": 5,
        "labels_down": 17,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "LCRY-1200": {
        "display_name": "Cryo-Tags 1.50 x 0.75",
        "label_width_in": 1.5,
        "label_height_in": 0.75,
        "top_margin_in": 0.31,
        "side_margin_in": 0.25,
        "vertical_pitch_in": 0.88,
        "horizontal_pitch_in": 1.63,
        "labels_across": 5,
        "labels_down": 12,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "LCRY-2380": {
        "display_name": "Cryo-Babies 0.94 x 0.50",
        "label_width_in": 0.94,
        "label_height_in": 0.5,
        "top_margin_in": 0.24,
        "side_margin_in": 0.56,
        "vertical_pitch_in": 0.63,
        "horizontal_pitch_in": 1.07,
        "labels_across": 7,
        "labels_down": 17,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "LCRY-1100": {
        "display_name": "Cryo-Tags 1.69 x 0.75",
        "label_width_in": 1.69,
        "label_height_in": 0.75,
        "top_margin_in": 0.63,
        "side_margin_in": 0.7,
        "vertical_pitch_in": 0.75,
        "horizontal_pitch_in": 1.8,
        "labels_across": 4,
        "labels_down": 13,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "LCRY-1258": {
        "display_name": "Cryo-Tags 2.625 x 1.0",
        "label_width_in": 2.625,
        "label_height_in": 1.0,
        "top_margin_in": 0.5,
        "side_margin_in": 0.19,
        "vertical_pitch_in": 1.0,
        "horizontal_pitch_in": 2.75,
        "labels_across": 3,
        "labels_down": 10,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "SIDE-1000": {
        "display_name": "Sidewall Cryo-Tags 1.50 x 0.25",
        "label_width_in": 1.5,
        "label_height_in": 0.25,
        "top_margin_in": 0.62,
        "side_margin_in": 0.5,
        "vertical_pitch_in": 0.25,
        "horizontal_pitch_in": 2.0,
        "labels_across": 4,
        "labels_down": 39,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "SPOT-1000": {
        "display_name": "Tough-Spots 3/8 in",
        "label_width_in": 0.38,
        "label_height_in": 0.38,
        "top_margin_in": 0.62,
        "side_margin_in": 0.69,
        "vertical_pitch_in": 0.63,
        "horizontal_pitch_in": 0.63,
        "labels_across": 12,
        "labels_down": 16,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "SPOT-2000": {
        "display_name": "Tough-Spots 1/2 in",
        "label_width_in": 0.5,
        "label_height_in": 0.5,
        "top_margin_in": 0.52,
        "side_margin_in": 0.52,
        "vertical_pitch_in": 0.63,
        "horizontal_pitch_in": 0.63,
        "labels_across": 12,
        "labels_down": 16,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "SPOT-3000": {
        "display_name": "Tough-Spots 3/4 in",
        "label_width_in": 0.75,
        "label_height_in": 0.75,
        "top_margin_in": 0.31,
        "side_margin_in": 0.35,
        "vertical_pitch_in": 0.88,
        "horizontal_pitch_in": 0.88,
        "labels_across": 9,
        "labels_down": 12,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "SPOT-4000": {
        "display_name": "Tough-Spots 1.00 in",
        "label_width_in": 1.0,
        "label_height_in": 1.0,
        "top_margin_in": 0.5,
        "side_margin_in": 0.35,
        "vertical_pitch_in": 1.13,
        "horizontal_pitch_in": 1.13,
        "labels_across": 7,
        "labels_down": 9,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
    "SPOT-5000": {
        "display_name": "Tough-Spots 7/16 in",
        "label_width_in": 0.44,
        "label_height_in": 0.44,
        "top_margin_in": 0.44,
        "side_margin_in": 0.59,
        "vertical_pitch_in": 0.57,
        "horizontal_pitch_in": 0.57,
        "labels_across": 13,
        "labels_down": 18,
        "page_width_in": 8.5,
        "page_height_in": 11.0,
    },
}
