label_templates = {
    "LCRY-1700": {
        "display_name": "Cryo-Babies 1.28 x 0.50",
        "template_path": "templates/LCRY-1700.docx",
        "labels_across": 5,
        "labels_down": 17,
        "chars_per_line": 30,
        "lines_per_label": 5,
        "default_font_size": 6,

    },
    "LCRY-1200": {
        "display_name": "Cryo-Tags 1.50 x 0.75",
        "template_path": "templates/LCRY-1200.docx",
        "labels_across": 5,
        "labels_down": 12,
        "chars_per_line": 35,
        "lines_per_label": 8,
        "default_font_size": 6,
    },
    "LCRY-2380": {
        "display_name": "Cryo-Babies 0.94 x 0.50",
        "template_path": "templates/LCRY-2380.docx",
        "labels_across": 7,
        "labels_down": 17,
        "chars_per_line": 25,
        "lines_per_label": 5,
        "default_font_size": 6,
    },
    "LCRY-1100": {
        "display_name": "Cryo-Tags 1.69 x 0.75",
        "template_path": "templates/LCRY-1100.docx",
        "labels_across": 4,
        "labels_down": 13,
        "chars_per_line": 45,
        "lines_per_label": 8,
        "default_font_size": 6,
    },
    "LCRY-1258": {
        "display_name": "Cryo-Tags 2.625 x 1.0",
        "template_path": "templates/LCRY-1258.docx",
        "labels_across": 3,
        "labels_down": 10,
        "chars_per_line": 32,
        "lines_per_label": 7,
        "default_font_size": 10,

    },
    "SIDE-1000": {
        "display_name": "Sidewall Cryo-Tags 1.50 x 0.25",
        "template_path": "templates/SIDE-1000.docx",
        "labels_across": 4,
        "labels_down": 39,
        "chars_per_line": 30,
        "lines_per_label": 2,
        "default_font_size": 7,
    },
    "SPOT-1000": {
        "display_name": "Tough-Spots 3/8 in",
        "template_path": "templates/SPOT-1000.docx",
        "labels_across": 12,
        "labels_down": 16,
        "chars_per_line": 10,
        "lines_per_label": 4,
        "default_font_size": 7,
    },
    "SPOT-2000": {
        "display_name": "Tough-Spots 1/2 in",
        "template_path": "templates/SPOT-2000.docx",
        "labels_across": 12,
        "labels_down": 16,
        "chars_per_line": 12,
        "lines_per_label": 5,
        "default_font_size": 7,
    },
    "SPOT-3000": {
        "display_name": "Tough-Spots 3/4 in",
        "template_path": "templates/SPOT-3000.docx",
        "labels_across": 9,
        "labels_down": 12,
        "chars_per_line": 12,
        "lines_per_label": 4,
        "default_font_size": 11,
    },
    "SPOT-4000": {
        "display_name": "Tough-Spots 1.00 in",
        "template_path": "templates/SPOT-4000.docx",
        "labels_across": 7,
        "labels_down": 9,
        "chars_per_line": 15,
        "lines_per_label": 4,
        "default_font_size": 12,
    },
    "SPOT-5000": {
        "display_name": "Tough-Spots 7/16 in",
        "template_path": "templates/SPOT-5000.docx",
        "labels_across": 13,
        "labels_down": 18,
        "chars_per_line": 15,
        "lines_per_label": 5,
        "default_font_size": 6,
    },
}
